name: Deploy Presentation
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        working-directory: ./presentation
      - name: Install slidev
        run:  npm i -g @slidev/cli
        working-directory: ./presentation
      - name: Build
        run: slidev build --base MameViewer
        working-directory: ./presentation
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./presentation/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}